In [1]:
from rightmove_webscraper import RightmoveData

In [2]:
sale_url = "https://www.rightmove.co.uk/property-for-sale/find.html?searchType=SALE&locationIdentifier=REGION%5E94346&insId=1&radius=0.0&minPrice=&maxPrice=&minBedrooms=&maxBedrooms=&displayPropertyType=&maxDaysSinceAdded=&_includeSSTC=on&sortByPriceDescending=&primaryDisplayPropertyType=&secondaryDisplayPropertyType=&oldDisplayPropertyType=&oldPrimaryDisplayPropertyType=&newHome=&auction=false"
rent_url = "https://www.rightmove.co.uk/property-to-rent/find.html?searchType=RENT&locationIdentifier=REGION%5E94346&insId=1&radius=0.0&minPrice=&maxPrice=&minBedrooms=&maxBedrooms=&displayPropertyType=&maxDaysSinceAdded=&sortByPriceDescending=&_includeLetAgreed=on&primaryDisplayPropertyType=&secondaryDisplayPropertyType=&oldDisplayPropertyType=&oldPrimaryDisplayPropertyType=&letType=&letFurnishType=&houseFlatShare="
bad_url = "https://www.rightmove.co.uk/property"
few_results_url = "https://www.rightmove.co.uk/property-for-sale/find.html?locationIdentifier=REGION%5E94346&radius=1.0&propertyTypes=&maxDaysSinceAdded=1&includeSSTC=false&mustHave=&dontShow=&furnishTypes=&keywords="

In [3]:
rmd = RightmoveData(few_results_url)

In [4]:
rmd.get_results

,price,type,address,url,agent_url,postcode,number_bedrooms,search_date
0,425000,2 bedroom flat for sale,"Wyvil Road, London SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,2.0,2019-10-07 20:56:11.626707
1,2700000,3 bedroom apartment for sale,"The Tower, St Georges Wharf, SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,3.0,2019-10-07 20:56:11.626707
2,2500000,3 bedroom house for sale,"The Gateways, Sprimont Place, London, SW3",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW3,3.0,2019-10-07 20:56:11.626707
3,2400000,3 bedroom apartment for sale,"Three Riverlight Quay, Nine Elms, London",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,3.0,2019-10-07 20:56:11.626707
4,1885000,4 bedroom apartment for sale,"York Mansions, Prince of Wales Drive, London, ...",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW11,4.0,2019-10-07 20:56:11.626707
5,1700000,2 bedroom apartment for sale,"Abell House, John Slip St, Westminster, London...",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW1P,2.0,2019-10-07 20:56:11.626707
6,1650000,3 bedroom apartment for sale,"Capital Building, New Union Square",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,3.0,2019-10-07 20:56:11.626707
7,1650000,2 bedroom apartment for sale,"The Corniche, 24 Albert Embankment, London",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,2.0,2019-10-07 20:56:11.626707
8,1350000,2 bedroom apartment for sale,Sloane Gardens Chelsea SW1W,http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW1W,2.0,2019-10-07 20:56:11.626707
9,1125000,3 bedroom apartment for sale,"Falkes House, 331 Kennington Lane, London, SE11",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SE11,3.0,2019-10-07 20:56:11.626707
10,1100000,2 bedroom flat for sale,"Ambassador Building, 5 New Union Square, Londo...",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW11,2.0,2019-10-07 20:56:11.626707
11,1017500,2 bedroom apartment for sale,"62-64 Wandsworth Road,\r\nLambeth,\r\nLondon,\...",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/developer/branch/Ba...,SW8,2.0,2019-10-07 20:56:11.626707
12,995000,3 bedroom terraced house for sale,"Sabine Road, SW11",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW11,3.0,2019-10-07 20:56:11.626707
13,950000,3 bedroom terraced house for sale,"Printers Road, Stockwell / Oval, SW9",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW9,3.0,2019-10-07 20:56:11.626707
14,900000,2 bedroom flat for sale,"Sky Gardens, Wandsworth Road, London, SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,2.0,2019-10-07 20:56:11.626707
15,815000,2 bedroom apartment for sale,"Riverlight Four, Riverlight Quay, Nine Elms, L...",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW11,2.0,2019-10-07 20:56:11.626707
16,775000,1 bedroom apartment for sale,"Capital Building, Embassy Gardens, Nine Elms",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,1.0,2019-10-07 20:56:11.626707
17,760000,2 bedroom apartment for sale,"Pinto Tower, Nine Elms Point, London",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,2.0,2019-10-07 20:56:11.626707
18,725000,3 bedroom terraced house for sale,"Bobbin Close, London, SW4",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW4,3.0,2019-10-07 20:56:11.626707
19,700000,2 bedroom apartment for sale,"Bridge House, St George Wharf, SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,2.0,2019-10-07 20:56:11.626707
20,650000,1 bedroom flat for sale,"Sloane Avenue, SW3",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW3,1.0,2019-10-07 20:56:11.626707
21,600000,2 bedroom flat for sale,"Grant House, 90 Liberty Street, London, SW9",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW9,2.0,2019-10-07 20:56:11.626707
22,600000,1 bedroom flat for sale,"Sloane Avenue, SW3",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW3,1.0,2019-10-07 20:56:11.626707
23,580000,1 bedroom apartment for sale,"Galleon House, St George Wharf, Vauxhall",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,1.0,2019-10-07 20:56:11.626707
24,550000,2 bedroom flat for sale,"Cambridge Road, Battersea, London, SW11",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW11,2.0,2019-10-07 20:56:11.626707
25,385000,2 bedroom flat for sale,"Deeley Road, Nine Elms, London, SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,2.0,2019-10-07 20:56:11.626707
26,470000,1 bedroom flat for sale,"Henry Wise House, SW1V, Pimlico, London, SW1V",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW1V,1.0,2019-10-07 20:56:11.626707
27,425000,2 bedroom flat for sale,"Wyvil Road, London SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,2.0,2019-10-07 20:56:11.626707
28,399999,1 bedroom property for sale,"Blenheim House, 180 Kings Road, London, SW3",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW3,1.0,2019-10-07 20:56:11.626707
29,385000,2 bedroom flat for sale,"Deeley Road, Nine Elms, London, SW8",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW8,2.0,2019-10-07 20:56:11.626707
30,375000,1 bedroom flat for sale,"Aldebert Terrace, South Lambeth",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,1.0,2019-10-07 20:56:11.626707
31,330000,Property for sale,"The Printworks, 139 Clapham Road, SW9",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW9,NaN,2019-10-07 20:56:11.626707
32,139950,1 bedroom flat for sale,"Paradise Walk, Bexhill-On-Sea",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,NaN,1.0,2019-10-07 20:56:11.626707
33,470000,1 bedroom flat for sale,"Henry Wise House, SW1V, Pimlico, London, SW1V",http://www.rightmove.co.uk/property-for-sale/p...,http://www.rightmove.co.uk/estate-agents/agent...,SW1V,1.0,2019-10-07 20:56:11.626707

In [18]:
for c in columns:
    df = rmd.summary(by=c)

In [19]:
rmd.summary()

   number_bedrooms  count          mean
0                0      9  9.949944e+05
1                1     16  1.103997e+06
2                2     37  1.810404e+06
3                3     12  5.695833e+06
4                4      1  5.100000e+06

In [22]:
rmd.results_count

78

In [23]:
rmd.results_count_display

76

In [6]:
import requests

r = requests.get("https://www.nytimes.com/2019/09/26/us/politics/who-is-whistleblower.html?action=click&module=Spotlight&pgtype=Homepage")

In [11]:
import pandas as pd
import numpy as np

df = pd.DataFrame(data={"c": [1, 2, 3, 4, 5], "b": np.nan})

In [12]:
df

   c   b
0  1 NaN
1  2 NaN
2  3 NaN
3  4 NaN
4  5 NaN